# Generated by Django 3.2.3 on 2021-06-10 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('experiencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='conferencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='conferencista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registro.conferencista'),
        ),
    ]
