# Generated by Django 3.2.3 on 2021-06-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_auto_20210610_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='conferencista',
        ),
        migrations.AddField(
            model_name='conferencia',
            name='conferencista',
            field=models.ManyToManyField(blank=True, to='app_registro.Conferencista'),
        ),
    ]
